import { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    managePlatform: 'Manage your eco platform',
    signOut: 'Sign Out',
    language: 'Language',
    dashboard: 'Dashboard',
    userManagement: 'User Management',
    userDetail: 'User Detail',
    activityLogs: 'Activity Logs',
    leaderboard: 'Leaderboard',
    customGreenActions: 'Custom Green Actions',
    milestones: 'Milestones',
    ecoBadges: 'Eco Badges',
    quests: 'Quests',
    rankLogs: 'Rank Logs',
    rankHistory: 'Rank History',
    achieved: 'Achieved',
    locked: 'Locked',
    achievedOn: 'Achieved on',
    achievedByUsers: 'Achieved by {count} users',
    noRankLogs: 'No Rank Logs',
    noRankLogsDesc: 'No rank progression data available yet.',
    addQuest: 'Add Quest',
    createQuest: 'Create Quest',
    updateQuest: 'Update Quest',
    saving: 'Saving...',
    achievedBy: 'Achieved by',
    users: 'users',
    target: 'Target',
    reward: 'Reward',
    menu: 'Menu',
    adminPanel: 'Admin Panel',
    adminDashboard: 'Admin Dashboard',
    loading: 'Loading...',
    search: 'Search',
    searchUsers: 'Search username or email...',
    all: 'All',
    today: 'Today',
    allTime: 'All Time',
    goodActions: 'Good Actions',
    badActions: 'Bad Actions',
    neutralNoSpecial: 'Neutral / No Special',
    customGreen: 'Custom Green',
    default: 'Default',
    date: 'Date',
    activity: 'Activity',
    type: 'Type',
    unit: 'Unit',
    category: 'Category',
    ecoPoint: 'Eco Point',
    status: 'Status',
    source: 'Source',
    description: 'Description',
    action: 'Action',
    good: 'Good',
    bad: 'Bad',
    neutral: 'Neutral',
    delete: 'Delete',
    pageOf: 'Page {page} of {total}',
    noData: 'No Data Available',
    noDataDesc: 'There is no data to display at the moment.',
    errorLoadingData: 'Error Loading Data',
    tryAgain: 'Try Again',
    noActivityLogs: 'No Activity Logs',
    noActivityLogsDesc: 'No activity logs found for the current filters.',
    noUsersFound: 'No Users Found',
    noUsersFoundDesc: 'No users match your current filters.',
    user: 'User',
    onboarding: 'Onboarding',
    complete: 'Complete',
    pending: 'Pending',
    ecoRatio: 'Eco Ratio',
    rank: 'Rank',
    lbRank: 'LB Rank',
    joined: 'Joined',
    view: 'View',
    totalUsers: 'Total Users',
    totalUnit: 'Total Unit',
    totalActivities: 'Total Activities',
    totalAktivitas: 'Total Activities',
    badRatio: 'Bad Ratio',
    questsCompleted: 'Quests Completed',
    ecoBadgesEarned: 'Eco Badges Earned',
    milestonesCompleted: 'Milestones Completed',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In to Admin',
    signingIn: 'Signing in...',
    adminLoginDesc: 'Sign in with an admin account to monitor frontend and backend activity.',
    adminPasswordPlaceholder: 'admin password',
    accessDenied: 'Access Denied',
    accessDeniedDesc: 'You do not have permission to access the admin panel.',
    backToLogin: 'Back to Login',
    name: 'Name',
    slug: 'Slug',
    icon: 'Icon',
    targetCu: 'Target CU',
    create: 'Create',
    update: 'Update',
    active: 'Active',
    notStarted: 'Not Started',
    noQuests: 'No Quests',
    noQuestsDesc: 'No quests data available.',
    completeThisQuest: 'Complete this quest',
    createBadge: 'Create Badge',
    updateBadge: 'Update Badge',
    noEcoBadges: 'No Eco Badges',
    noEcoBadgesDesc: 'No eco badges data available.',
    meetRequirements: 'Meet the requirements',
    noMilestones: 'No Milestones',
    noMilestonesDesc: 'No milestones data available.',
    completeThisMilestone: 'Complete this milestone',
    userId: 'User ID',
    actionName: 'Action name',
    noCustomGreenActions: 'No Custom Green Actions',
    noCustomGreenActionsDesc: 'No custom green actions have been created yet.',
    leaderboardEmpty: 'Leaderboard Empty',
    leaderboardEmptyDesc: 'No leaderboard data available.',
    ecoScore: 'Eco Score',
    pts: 'pts',
    overview: 'Overview',
    greenActions: 'Green Actions',
    progress: 'Progress',
    admin: 'Admin',
    registered: 'Registered',
    lastLogin: 'Last Login',
    role: 'Role',
    completedAt: 'Completed At',
    lastStep: 'Last Step',
    guidebookViewed: 'Guidebook Viewed',
    lastDailySurvey: 'Last Daily Survey',
    totalActivity: 'Total Activity',
    customGreenShort: 'Custom Green',
    questsDone: 'Quests Done',
    badgesEarned: 'Badges Earned',
    currentRank: 'Current Rank',
    lbPosition: 'LB Position',
    yes: 'Yes',
    no: 'No',
    systemFeedback: 'System Feedback',
    recommendation: 'Recommendation',
    userNotFound: 'User Not Found',
    userNotFoundDesc: 'The requested user could not be found.',
    noUserCustomGreenDesc: "This user hasn't created any custom green actions yet.",
    created: 'Created',
    milestoneDescFallback: 'Complete this milestone',
    badgeDescFallback: 'Meet the requirements',
    guestDesc: 'Starting your eco journey',
    explorerDesc: 'Exploring green actions',
    guardianDesc: 'Guarding the environment',
    heroDesc: 'Eco Hero status achieved',
    guest: 'Guest',
    explorer: 'Explorer',
    guardian: 'Guardian',
    hero: 'Hero',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    avgEcoRatio: 'Average Eco Ratio',
    activityTrend: 'Activity Trend',
    actionsDistribution: 'Actions Distribution',
    noChartData: 'No chart data available. Connect your API to visualize trends.',
    noActionData: 'No action data available yet.',
    apiUnavailable: 'API not available. Connect your backend to see live data.',
    filters: 'Filters',
    clear: 'Clear',
    fetchUsersError: 'Unable to fetch users. Make sure the API is connected.',
    fetchLeaderboardError: 'Unable to fetch leaderboard. Make sure the API is connected.',
    addEcoBadge: 'Add Eco Badge',
    earnedBy: 'Earned by',
    addMilestone: 'Add Milestone',
    addCustomAction: 'Add Custom Action',
    fetchEcoBadgesError: 'Unable to fetch eco badges. Make sure the API is connected.',
    fetchMilestonesError: 'Unable to fetch milestones. Make sure the API is connected.',
    fetchCustomGreenError: 'Unable to fetch custom green actions. Make sure the API is connected.',
  },
  id: {
    managePlatform: 'Kelola platform eco kamu',
    signOut: 'Keluar',
    language: 'Bahasa',
    dashboard: 'Dashboard',
    userManagement: 'Manajemen User',
    userDetail: 'Detail User',
    activityLogs: 'Log Aktivitas',
    leaderboard: 'Peringkat',
    customGreenActions: 'Aksi Hijau Custom',
    milestones: 'Milestone',
    ecoBadges: 'Eco Badge',
    quests: 'Misi',
    rankLogs: 'Log Rank',
    rankHistory: 'Riwayat Rank',
    achieved: 'Tercapai',
    locked: 'Terkunci',
    achievedOn: 'Dicapai pada',
    achievedByUsers: 'Dicapai oleh {count} user',
    noRankLogs: 'Belum Ada Log Rank',
    noRankLogsDesc: 'Belum ada data pencapaian rank.',
    addQuest: 'Tambah Misi',
    createQuest: 'Buat Misi',
    updateQuest: 'Perbarui Misi',
    saving: 'Menyimpan...',
    achievedBy: 'Dicapai oleh',
    users: 'user',
    target: 'Target',
    reward: 'Reward',
    menu: 'Menu',
    adminPanel: 'Panel Admin',
    adminDashboard: 'Dashboard Admin',
    loading: 'Memuat...',
    search: 'Cari',
    searchUsers: 'Cari username atau email...',
    all: 'Semua',
    today: 'Hari Ini',
    allTime: 'Semua Waktu',
    goodActions: 'Aksi Baik',
    badActions: 'Aksi Buruk',
    neutralNoSpecial: 'Netral / Tidak Khusus',
    customGreen: 'Aksi Hijau Custom',
    default: 'Default',
    date: 'Tanggal',
    activity: 'Aktivitas',
    type: 'Tipe',
    unit: 'Unit',
    category: 'Kategori',
    ecoPoint: 'Eco Point',
    status: 'Status',
    source: 'Sumber',
    description: 'Deskripsi',
    action: 'Aksi',
    good: 'Baik',
    bad: 'Buruk',
    neutral: 'Netral',
    delete: 'Hapus',
    pageOf: 'Halaman {page} dari {total}',
    noData: 'Tidak Ada Data',
    noDataDesc: 'Belum ada data untuk ditampilkan saat ini.',
    errorLoadingData: 'Gagal Memuat Data',
    tryAgain: 'Coba Lagi',
    noActivityLogs: 'Tidak Ada Log Aktivitas',
    noActivityLogsDesc: 'Tidak ada log aktivitas untuk filter ini.',
    noUsersFound: 'User Tidak Ditemukan',
    noUsersFoundDesc: 'Tidak ada user yang cocok dengan filter saat ini.',
    user: 'User',
    onboarding: 'Onboarding',
    complete: 'Selesai',
    pending: 'Menunggu',
    ecoRatio: 'Rasio Eco',
    rank: 'Rank',
    lbRank: 'Rank LB',
    joined: 'Bergabung',
    view: 'Lihat',
    totalUsers: 'Total User',
    totalUnit: 'Total Unit',
    totalActivities: 'Total Aktivitas',
    totalAktivitas: 'Total Aktivitas',
    badRatio: 'Rasio Buruk',
    questsCompleted: 'Misi Selesai',
    ecoBadgesEarned: 'Eco Badge Didapat',
    milestonesCompleted: 'Milestone Selesai',
    username: 'Username',
    password: 'Password',
    signIn: 'Masuk ke Admin',
    signingIn: 'Sedang masuk...',
    adminLoginDesc: 'Masuk dengan akun admin untuk memantau aktivitas frontend dan backend.',
    adminPasswordPlaceholder: 'password admin',
    accessDenied: 'Akses Ditolak',
    accessDeniedDesc: 'Kamu tidak punya izin untuk mengakses panel admin.',
    backToLogin: 'Kembali ke Login',
    name: 'Nama',
    slug: 'Slug',
    icon: 'Ikon',
    targetCu: 'Target CU',
    create: 'Buat',
    update: 'Perbarui',
    active: 'Aktif',
    notStarted: 'Belum Mulai',
    noQuests: 'Tidak Ada Misi',
    noQuestsDesc: 'Belum ada data misi.',
    completeThisQuest: 'Selesaikan misi ini',
    createBadge: 'Buat Badge',
    updateBadge: 'Perbarui Badge',
    noEcoBadges: 'Tidak Ada Eco Badge',
    noEcoBadgesDesc: 'Belum ada data eco badge.',
    meetRequirements: 'Penuhi syarat yang dibutuhkan',
    noMilestones: 'Tidak Ada Milestone',
    noMilestonesDesc: 'Belum ada data milestone.',
    completeThisMilestone: 'Selesaikan milestone ini',
    userId: 'ID User',
    actionName: 'Nama aksi',
    noCustomGreenActions: 'Tidak Ada Aksi Hijau Custom',
    noCustomGreenActionsDesc: 'Belum ada aksi hijau custom yang dibuat.',
    leaderboardEmpty: 'Peringkat Kosong',
    leaderboardEmptyDesc: 'Belum ada data peringkat.',
    ecoScore: 'Skor Eco',
    pts: 'poin',
    overview: 'Ringkasan',
    greenActions: 'Aksi Hijau',
    progress: 'Progress',
    admin: 'Admin',
    registered: 'Terdaftar',
    lastLogin: 'Login Terakhir',
    role: 'Role',
    completedAt: 'Selesai Pada',
    lastStep: 'Step Terakhir',
    guidebookViewed: 'Panduan Dilihat',
    lastDailySurvey: 'Survey Harian Terakhir',
    totalActivity: 'Total Aktivitas',
    customGreenShort: 'Custom Green',
    questsDone: 'Misi Selesai',
    badgesEarned: 'Badge Didapat',
    currentRank: 'Rank Saat Ini',
    lbPosition: 'Posisi LB',
    yes: 'Ya',
    no: 'Tidak',
    systemFeedback: 'Feedback Sistem',
    recommendation: 'Rekomendasi',
    userNotFound: 'User Tidak Ditemukan',
    userNotFoundDesc: 'User yang diminta tidak ditemukan.',
    noUserCustomGreenDesc: 'User ini belum membuat aksi hijau custom.',
    created: 'Dibuat',
    milestoneDescFallback: 'Selesaikan milestone ini',
    badgeDescFallback: 'Penuhi syarat yang dibutuhkan',
    guestDesc: 'Mulai perjalanan eco kamu',
    explorerDesc: 'Menjelajahi aksi hijau',
    guardianDesc: 'Menjaga lingkungan',
    heroDesc: 'Status eco hero tercapai',
    guest: 'Tamu',
    explorer: 'Penjelajah',
    guardian: 'Penjaga',
    hero: 'Pahlawan',
    last7Days: '7 Hari Terakhir',
    last30Days: '30 Hari Terakhir',
    avgEcoRatio: 'Rata-rata Rasio Eco',
    activityTrend: 'Tren Aktivitas',
    actionsDistribution: 'Distribusi Aksi',
    noChartData: 'Belum ada data grafik. Hubungkan API untuk melihat tren.',
    noActionData: 'Belum ada data aksi.',
    apiUnavailable: 'API tidak tersedia. Hubungkan backend untuk melihat data live.',
    filters: 'Filter',
    clear: 'Bersihkan',
    fetchUsersError: 'Tidak bisa mengambil data user. Pastikan API terhubung.',
    fetchLeaderboardError: 'Tidak bisa mengambil data peringkat. Pastikan API terhubung.',
    addEcoBadge: 'Tambah Eco Badge',
    earnedBy: 'Didapat oleh',
    addMilestone: 'Tambah Milestone',
    addCustomAction: 'Tambah Aksi Custom',
    fetchEcoBadgesError: 'Tidak bisa mengambil data eco badge. Pastikan API terhubung.',
    fetchMilestonesError: 'Tidak bisa mengambil data milestone. Pastikan API terhubung.',
    fetchCustomGreenError: 'Tidak bisa mengambil data aksi hijau custom. Pastikan API terhubung.',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('admin_language') || 'en');

  const value = useMemo(() => ({
    language,
    setLanguage: (next) => {
      localStorage.setItem('admin_language', next);
      setLanguage(next);
    },
    t: (key, values = {}) => {
      let text = translations[language]?.[key] || translations.en[key] || key;
      Object.entries(values).forEach(([name, value]) => {
        text = text.replace(`{${name}}`, value);
      });
      return text;
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useAdminLanguage() {
  return useContext(LanguageContext);
}
