import { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    managePlatform: 'Manage your eco platform',
    signOut: 'Sign Out',
    language: 'Language',
    dashboard: 'Dashboard',
    userManagement: 'User Management',
    surveyLogs: 'Survey Logs',
    userDetail: 'User Detail',
    activityLogs: 'Activity Logs',
    leaderboard: 'Leaderboard',
    customGreenActions: 'Custom Green Actions',
    milestones: 'Achievements',
    ecoBadges: 'Eco Badges',
    quests: 'Quests',
    rankLogs: 'Rank Logs',
    rankHistory: 'Rank History',
    achieved: 'Achieved',
    locked: 'Locked',
    achievedOn: 'Achieved on',
    achievedByUsers: 'Achieved by {count} users',
    noRankLogs: 'No Rank Logs',
    noRankLogsDesc: 'No rank progression data available yet.',
    addQuest: 'Add Quest',
    createQuest: 'Create Quest',
    updateQuest: 'Update Quest',
    saving: 'Saving...',
    achievedBy: 'Achieved by',
    users: 'users',
    target: 'Target',
    reward: 'Reward',
    requires: 'Requires',
    journeyPoints: 'Journey Points',
    targetJourneyPoints: 'Target Journey Points',
    carbonUnit: 'Carbon Unit (CU)',
    targetCarbonUnit: 'Target Carbon Unit (CU)',
    requirementCarbonUnit: 'Requirement Carbon Unit (CU)',
    rewardJourneyPoints: 'Reward Journey Points',
    addRank: 'Add Rank',
    createRank: 'Create Rank',
    rankName: 'Rank Name',
    rankType: 'Rank Type',
    rankNamePlaceholder: 'Type a new rank name',
    saveRankError: 'Unable to save rank.',
    deleteRankError: 'Unable to delete rank.',
    rankAdded: 'Rank added',
    editRank: 'Edit rank',
    deleteRank: 'Delete rank',
    deleteRankConfirm: 'Delete rank "{name}"?',
    menu: 'Menu',
    adminPanel: 'Admin Panel',
    adminDashboard: 'Admin Dashboard',
    loading: 'Loading...',
    search: 'Search',
    searchUsers: 'Search username or email...',
    all: 'All',
    today: 'Today',
    allTime: 'All Time',
    goodActions: 'Good Actions',
    badActions: 'Bad Actions',
    neutralNoSpecial: 'Neutral / No Special',
    customGreen: 'Custom Green',
    custom: 'Custom',
    default: 'Default',
    date: 'Date',
    activity: 'Activity',
    type: 'Type',
    unit: 'Unit',
    category: 'Category',
    ecoPoint: 'Eco Point',
    status: 'Status',
    source: 'Source',
    description: 'Description',
    action: 'Action',
    good: 'Good',
    bad: 'Bad',
    neutral: 'Neutral',
    delete: 'Delete',
    detail: 'Detail',
    pageOf: 'Page {page} of {total}',
    noData: 'No Data Available',
    noDataDesc: 'There is no data to display at the moment.',
    errorLoadingData: 'Error Loading Data',
    tryAgain: 'Try Again',
    noActivityLogs: 'No Activity Logs',
    noActivityLogsDesc: 'No activity logs found for the current filters.',
    noUsersFound: 'No Users Found',
    noUsersFoundDesc: 'No users match your current filters.',
    user: 'User',
    onboarding: 'Onboarding',
    complete: 'Complete',
    completed: 'Completed',
    notCompleted: 'Not Completed',
    pending: 'Pending',
    ecoRatio: 'Eco Ratio',
    rank: 'Rank',
    lbRank: 'LB Rank',
    joined: 'Joined',
    view: 'View',
    totalUsers: 'Total Users',
    totalUnit: 'Total Unit',
    totalActivities: 'Total Activities',
    totalAktivitas: 'Total Activities',
    badRatio: 'Bad Ratio',
    questsCompleted: 'Quests Completed',
    ecoBadgesEarned: 'Eco Badges Earned',
    milestonesCompleted: 'Achievements Completed',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In to Admin',
    signingIn: 'Signing in...',
    adminLoginDesc: 'Sign in with an admin account to monitor frontend and backend activity.',
    adminPasswordPlaceholder: 'admin password',
    accessDenied: 'Access Denied',
    accessDeniedDesc: 'You do not have permission to access the admin panel.',
    backToLogin: 'Back to Login',
    name: 'Name',
    slug: 'Slug',
    icon: 'Icon',
    targetCu: 'Requirement Carbon Unit (CU)',
    create: 'Create',
    update: 'Update',
    active: 'Active',
    notStarted: 'Not Started',
    noQuests: 'No Quests',
    noQuestsDesc: 'No quests data available.',
    completeThisQuest: 'Complete this quest',
    createBadge: 'Create Badge',
    updateBadge: 'Update Badge',
    noEcoBadges: 'No Eco Badges',
    noEcoBadgesDesc: 'No eco badges data available.',
    meetRequirements: 'Meet the requirements',
    noMilestones: 'No Achievements',
    noMilestonesDesc: 'No achievements data available.',
    completeThisMilestone: 'Complete this achievement',
    userId: 'User ID',
    actionName: 'Action name',
    noCustomGreenActions: 'No Custom Green Actions',
    noCustomGreenActionsDesc: 'No custom green actions have been created yet.',
    leaderboardEmpty: 'Leaderboard Empty',
    leaderboardEmptyDesc: 'No leaderboard data available.',
    ecoScore: 'Eco Score',
    pts: 'pts',
    overview: 'Overview',
    greenActions: 'Green Actions',
    progress: 'Progress',
    admin: 'Admin',
    registered: 'Registered',
    lastLogin: 'Last Login',
    role: 'Role',
    completedAt: 'Completed At',
    lastStep: 'Last Step',
    guidebookViewed: 'Guidebook Viewed',
    lastDailySurvey: 'Last Daily Survey',
    totalActivity: 'Total Activity',
    customGreenShort: 'Custom Green',
    questsDone: 'Quests Done',
    badgesEarned: 'Badges Earned',
    currentRank: 'Current Rank',
    lbPosition: 'LB Position',
    yes: 'Yes',
    no: 'No',
    systemFeedback: 'System Feedback',
    recommendation: 'Recommendation',
    userNotFound: 'User Not Found',
    userNotFoundDesc: 'The requested user could not be found.',
    noUserCustomGreenDesc: "This user hasn't created any custom green actions yet.",
    created: 'Created',
    milestoneDescFallback: 'Complete this achievement',
    badgeDescFallback: 'Meet the requirements',
    guestDesc: 'Starting your eco journey',
    explorerDesc: 'Exploring green actions',
    guardianDesc: 'Guarding the environment',
    heroDesc: 'Eco Hero status achieved',
    customRankDesc: 'Custom rank type',
    guest: 'Guest',
    explorer: 'Explorer',
    guardian: 'Guardian',
    hero: 'Hero',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    avgEcoRatio: 'Average Eco Ratio',
    activityTrend: 'Activity Trend',
    actionsDistribution: 'Actions Distribution',
    noChartData: 'No chart data available. Connect your API to visualize trends.',
    noActionData: 'No action data available yet.',
    apiUnavailable: 'API not available. Connect your backend to see live data.',
    filters: 'Filters',
    clear: 'Clear',
    cancel: 'Cancel',
    fetchUsersError: 'Unable to fetch users. Make sure the API is connected.',
    fetchSurveyLogsError: 'Unable to fetch survey logs. Make sure the API is connected.',
    dailySurvey: 'Daily Survey',
    surveyDate: 'Survey Date',
    autoRefresh: 'Auto refresh every 10 seconds',
    nextReset: 'Next reset',
    resetIn: 'Reset in',
    reloadData: 'Reload Data',
    surveyHistory: 'Survey Log History',
    noSurveyLogs: 'No Survey Logs',
    noSurveyLogsDesc: 'No daily survey status is available yet.',
    noSurveyHistory: 'No Survey History',
    noSurveyHistoryDesc: 'This user has not completed any survey yet.',
    deleteUserConfirm: 'Delete this user? This action cannot be undone.',
    fetchLeaderboardError: 'Unable to fetch leaderboard. Make sure the API is connected.',
    addEcoBadge: 'Add Eco Badge',
    earnedBy: 'Earned by',
    addMilestone: 'Add Achievement',
    addCustomAction: 'Add Custom Action',
    fetchEcoBadgesError: 'Unable to fetch eco badges. Make sure the API is connected.',
    fetchMilestonesError: 'Unable to fetch achievements. Make sure the API is connected.',
    fetchCustomGreenError: 'Unable to fetch custom green actions. Make sure the API is connected.',
    fetchQuestsError: 'Unable to fetch quests. Make sure the API is connected.',
    fetchActivityLogsError: 'Unable to fetch activity logs. Make sure the API is connected.',
    fetchUserDetailError: 'Unable to fetch user details.',
    fetchProgressError: 'Unable to fetch progress data.',
    fetchRankLogsError: 'Unable to fetch rank logs.',
    fetchPointLogsError: 'Unable to fetch point logs.',
    saveMilestoneError: 'Unable to save achievement.',
    saveEcoBadgeError: 'Unable to save eco badge.',
    saveCustomGreenError: 'Unable to save custom green action.',
    saveQuestError: 'Unable to save quest.',
    transportation: 'Transportation',
    waste: 'Waste',
    consumption: 'Consumption',
    energy: 'Energy',
    environment: 'Environment',
    school: 'School',
    homeCategory: 'Home',
    pointLogs: 'Point Logs',
    pointLogDesc: 'Daily point changes and cumulative progression',
    pointsIn: 'Points In',
    pointsOut: 'Points Out',
    netPoints: 'Net Points',
    cumulative: 'Cumulative',
    pointChartTitle: 'Point Progression Chart',
    noPointData: 'No point data available for this user.',
    points: 'Points',
    dailyPoints: 'Daily Points',
    totalCumulative: 'Total Cumulative',
  },
  id: {
    managePlatform: 'Kelola platform eco kamu',
    signOut: 'Keluar',
    language: 'Bahasa',
    dashboard: 'Dashboard',
    userManagement: 'Manajemen User',
    surveyLogs: 'Log Survei',
    userDetail: 'Detail User',
    activityLogs: 'Log Aktivitas',
    leaderboard: 'Peringkat',
    customGreenActions: 'Aksi Hijau Kustom',
    milestones: 'Pencapaian',
    ecoBadges: 'Eco Badge',
    quests: 'Misi',
    rankLogs: 'Log Pangkat',
    rankHistory: 'Riwayat Rank',
    achieved: 'Tercapai',
    locked: 'Terkunci',
    achievedOn: 'Dicapai pada',
    achievedByUsers: 'Dicapai oleh {count} user',
    noRankLogs: 'Belum Ada Log Rank',
    noRankLogsDesc: 'Belum ada data pencapaian rank.',
    addQuest: 'Tambah Misi',
    createQuest: 'Buat Misi',
    updateQuest: 'Perbarui Misi',
    saving: 'Menyimpan...',
    achievedBy: 'Dicapai oleh',
    users: 'user',
    target: 'Target',
    reward: 'Hadiah',
    requires: 'Syarat',
    journeyPoints: 'Poin Perjalanan',
    targetJourneyPoints: 'Target Poin Perjalanan',
    carbonUnit: 'Carbon Unit (CU)',
    targetCarbonUnit: 'Target Carbon Unit (CU)',
    requirementCarbonUnit: 'Syarat Carbon Unit (CU)',
    rewardJourneyPoints: 'Hadiah Poin Perjalanan',
    addRank: 'Tambah Pangkat',
    createRank: 'Tambah Pangkat',
    rankName: 'Nama Pangkat',
    rankType: 'Jenis Rank',
    rankNamePlaceholder: 'Ketik nama rank baru',
    saveRankError: 'Tidak bisa menyimpan pangkat.',
    deleteRankError: 'Tidak bisa menghapus pangkat.',
    rankAdded: 'Pangkat ditambahkan',
    editRank: 'Edit pangkat',
    deleteRank: 'Hapus pangkat',
    deleteRankConfirm: 'Hapus pangkat "{name}"?',
    menu: 'Menu',
    adminPanel: 'Panel Admin',
    adminDashboard: 'Dashboard Admin',
    loading: 'Memuat...',
    search: 'Cari',
    searchUsers: 'Cari username atau email...',
    all: 'Semua',
    today: 'Hari Ini',
    allTime: 'Semua Waktu',
    goodActions: 'Aksi Baik',
    badActions: 'Aksi Buruk',
    neutralNoSpecial: 'Netral / Tidak Khusus',
    customGreen: 'Aksi Hijau Custom',
    custom: 'Custom',
    default: 'Default',
    date: 'Tanggal',
    activity: 'Aktivitas',
    type: 'Tipe',
    unit: 'Unit',
    category: 'Kategori',
    ecoPoint: 'Eco Point',
    status: 'Status',
    source: 'Sumber',
    description: 'Deskripsi',
    action: 'Aksi',
    good: 'Baik',
    bad: 'Buruk',
    neutral: 'Netral',
    delete: 'Hapus',
    detail: 'Detail',
    pageOf: 'Halaman {page} dari {total}',
    noData: 'Tidak Ada Data',
    noDataDesc: 'Belum ada data untuk ditampilkan saat ini.',
    errorLoadingData: 'Gagal Memuat Data',
    tryAgain: 'Coba Lagi',
    noActivityLogs: 'Tidak Ada Log Aktivitas',
    noActivityLogsDesc: 'Tidak ada log aktivitas untuk filter ini.',
    noUsersFound: 'User Tidak Ditemukan',
    noUsersFoundDesc: 'Tidak ada user yang cocok dengan filter saat ini.',
    user: 'User',
    onboarding: 'Onboarding',
    complete: 'Selesai',
    completed: 'Selesai',
    notCompleted: 'Belum selesai',
    pending: 'Menunggu',
    ecoRatio: 'Rasio Eco',
    rank: 'Rank',
    lbRank: 'Rank LB',
    joined: 'Bergabung',
    view: 'Lihat',
    totalUsers: 'Total User',
    totalUnit: 'Total Unit',
    totalActivities: 'Total Aktivitas',
    totalAktivitas: 'Total Aktivitas',
    badRatio: 'Rasio Buruk',
    questsCompleted: 'Misi Selesai',
    ecoBadgesEarned: 'Lencana Eco Didapat',
    milestonesCompleted: 'Pencapaian Selesai',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    signIn: 'Masuk ke Admin',
    signingIn: 'Sedang masuk...',
    adminLoginDesc: 'Masuk dengan akun admin untuk memantau aktivitas frontend dan backend.',
    adminPasswordPlaceholder: 'password admin',
    accessDenied: 'Akses Ditolak',
    accessDeniedDesc: 'Kamu tidak punya izin untuk mengakses panel admin.',
    backToLogin: 'Kembali ke Login',
    name: 'Nama',
    slug: 'Slug',
    icon: 'Ikon',
    targetCu: 'Syarat Carbon Unit (CU)',
    create: 'Buat',
    update: 'Perbarui',
    active: 'Aktif',
    notStarted: 'Belum Mulai',
    noQuests: 'Tidak Ada Misi',
    noQuestsDesc: 'Belum ada data misi.',
    completeThisQuest: 'Selesaikan misi ini',
    createBadge: 'Buat Badge',
    updateBadge: 'Perbarui Badge',
    noEcoBadges: 'Tidak Ada Eco Badge',
    noEcoBadgesDesc: 'Belum ada data eco badge.',
    meetRequirements: 'Penuhi syarat yang dibutuhkan',
    noMilestones: 'Tidak Ada Pencapaian',
    noMilestonesDesc: 'Belum ada data pencapaian.',
    completeThisMilestone: 'Selesaikan pencapaian ini',
    userId: 'ID User',
    actionName: 'Nama aksi',
    noCustomGreenActions: 'Tidak Ada Aksi Hijau Custom',
    noCustomGreenActionsDesc: 'Belum ada aksi hijau custom yang dibuat.',
    leaderboardEmpty: 'Peringkat Kosong',
    leaderboardEmptyDesc: 'Belum ada data peringkat.',
    ecoScore: 'Skor Eco',
    pts: 'poin',
    overview: 'Ringkasan',
    greenActions: 'Aksi Hijau',
    progress: 'Progress',
    admin: 'Admin',
    registered: 'Terdaftar',
    lastLogin: 'Login Terakhir',
    role: 'Role',
    completedAt: 'Selesai Pada',
    lastStep: 'Step Terakhir',
    guidebookViewed: 'Panduan Dilihat',
    lastDailySurvey: 'Survey Harian Terakhir',
    totalActivity: 'Total Aktivitas',
    customGreenShort: 'Aksi Hijau Kustom',
    questsDone: 'Misi Selesai',
    badgesEarned: 'Badge Didapat',
    currentRank: 'Rank Saat Ini',
    lbPosition: 'Posisi LB',
    yes: 'Ya',
    no: 'Tidak',
    systemFeedback: 'Feedback Sistem',
    recommendation: 'Rekomendasi',
    userNotFound: 'User Tidak Ditemukan',
    userNotFoundDesc: 'User yang diminta tidak ditemukan.',
    noUserCustomGreenDesc: 'User ini belum membuat aksi hijau custom.',
    created: 'Dibuat',
    milestoneDescFallback: 'Selesaikan pencapaian ini',
    badgeDescFallback: 'Penuhi syarat yang dibutuhkan',
    guestDesc: 'Mulai perjalanan eco kamu',
    explorerDesc: 'Menjelajahi aksi hijau',
    guardianDesc: 'Menjaga lingkungan',
    heroDesc: 'Status eco hero tercapai',
    customRankDesc: 'Jenis rank custom',
    guest: 'Tamu',
    explorer: 'Penjelajah',
    guardian: 'Penjaga',
    hero: 'Pahlawan',
    last7Days: '7 Hari Terakhir',
    last30Days: '30 Hari Terakhir',
    avgEcoRatio: 'Rata-rata Rasio Eco',
    activityTrend: 'Tren Aktivitas',
    actionsDistribution: 'Distribusi Aksi',
    noChartData: 'Belum ada data grafik. Hubungkan API untuk melihat tren.',
    noActionData: 'Belum ada data aksi.',
    apiUnavailable: 'API tidak tersedia. Hubungkan backend untuk melihat data live.',
    filters: 'Filter',
    clear: 'Bersihkan',
    cancel: 'Batal',
    fetchUsersError: 'Tidak bisa mengambil data user. Pastikan API terhubung.',
    fetchSurveyLogsError: 'Tidak bisa mengambil log survei. Pastikan API terhubung.',
    dailySurvey: 'Survei Harian',
    surveyDate: 'Tanggal Survei',
    autoRefresh: 'Refresh otomatis setiap 10 detik',
    nextReset: 'Reset berikutnya',
    resetIn: 'Reset dalam',
    reloadData: 'Muat Ulang Data',
    surveyHistory: 'Sejarah Log Survei',
    noSurveyLogs: 'Tidak Ada Log Survei',
    noSurveyLogsDesc: 'Belum ada status daily survei untuk ditampilkan.',
    noSurveyHistory: 'Tidak Ada Sejarah Survei',
    noSurveyHistoryDesc: 'User ini belum pernah menyelesaikan survei.',
    deleteUserConfirm: 'Hapus user ini? Aksi ini tidak bisa dibatalkan.',
    fetchLeaderboardError: 'Tidak bisa mengambil data peringkat. Pastikan API terhubung.',
    addEcoBadge: 'Tambah Eco Badge',
    earnedBy: 'Didapat oleh',
    addMilestone: 'Tambah Pencapaian',
    addCustomAction: 'Tambah Aksi Custom',
    fetchEcoBadgesError: 'Tidak bisa mengambil data eco badge. Pastikan API terhubung.',
    fetchMilestonesError: 'Tidak bisa mengambil data pencapaian. Pastikan API terhubung.',
    fetchCustomGreenError: 'Tidak bisa mengambil data aksi hijau custom. Pastikan API terhubung.',
    fetchQuestsError: 'Tidak bisa mengambil data misi. Pastikan API terhubung.',
    fetchActivityLogsError: 'Tidak bisa mengambil log aktivitas. Pastikan API terhubung.',
    fetchUserDetailError: 'Tidak bisa mengambil detail user.',
    fetchProgressError: 'Tidak bisa mengambil data progress.',
    fetchRankLogsError: 'Tidak bisa mengambil log rank.',
    fetchPointLogsError: 'Tidak bisa mengambil data poin.',
    saveMilestoneError: 'Tidak bisa menyimpan pencapaian.',
    saveEcoBadgeError: 'Tidak bisa menyimpan eco badge.',
    saveCustomGreenError: 'Tidak bisa menyimpan aksi hijau custom.',
    saveQuestError: 'Tidak bisa menyimpan misi.',
    transportation: 'Transportasi',
    waste: 'Sampah',
    consumption: 'Konsumsi',
    energy: 'Energi',
    environment: 'Lingkungan',
    school: 'Sekolah',
    homeCategory: 'Rumah',
    pointLogs: 'Log Poin',
    pointLogDesc: 'Perubahan poin harian dan progres kumulatif',
    pointsIn: 'Poin Masuk',
    pointsOut: 'Poin Keluar',
    netPoints: 'Poin Bersih',
    cumulative: 'Kumulatif',
    pointChartTitle: 'Grafik Progres Poin',
    noPointData: 'Belum ada data poin untuk user ini.',
    points: 'Poin',
    dailyPoints: 'Poin Harian',
    totalCumulative: 'Total Kumulatif',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('admin_language') || 'id');

  const value = useMemo(() => ({
    language,
    setLanguage: (next) => {
      localStorage.setItem('admin_language', next);
      setLanguage(next);
    },
    t: (key, values = {}) => {
      let text = translations[language]?.[key] || translations.en[key] || key;
      Object.entries(values).forEach(([name, value]) => {
        text = text.replace(`{${name}}`, value);
      });
      return text;
    },
    label: (value, fallback = '—') => {
      if (value === null || value === undefined || value === '') return fallback;
      const key = String(value).trim().replace(/\s+/g, '').replace(/^[A-Z]/, (char) => char.toLowerCase());
      const lowerKey = String(value).trim().toLowerCase().replace(/\s+/g, '');
      return translations[language]?.[key] || translations[language]?.[lowerKey] || translations.en[key] || value;
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useAdminLanguage() {
  return useContext(LanguageContext);
}
